blank_issues_enabled: false
contact_links:
  - name: Security report
    url: https://github.com/pancudaniel7/blockscan-ethereum-service/security/advisories
    about: Please report security vulnerabilities here (private).
