global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: loki
    static_configs:
      - targets: ["loki:3100"]

  - job_name: blockscan
    metrics_path: /metrics
    static_configs:
      - targets: ["blockscan-replica1:8081"]
        labels:
          service: blockscan
          replica: blockscan-service-replica1
      - targets: ["blockscan-replica2:8081"]
        labels:
          service: blockscan
          replica: blockscan-service-replica2



  - job_name: telegraf
    static_configs:
      - targets: ["telegraf:9273"]
